Fix km and gk reconnection.
linaro-swg/kmgk pull request #13
Opened 2019-08-22 07:12 UTC by omasse-linaro

Do not close TEE connection when doing TA re-connection.

2019-08-22 18:22 UTC, vchong requested changes
>  km3: Move TEE context init/finalize in optee keymaster class constructor.

I think this is a bit inaccurate. Maybe something like `keymaster: Move TEE context init/finalize into its own initialization function`. Also, please add some description in the commit message as to why this is done.

> gk: Move TEE context init/finalize in optee gatekeeper class constructor/destructor.

Please change this to `gatekeeper: Move TEE context init/finalize calling function directly into OpteeIPC gatekeeper class constructor/destructor.`, and also same as above, add description in the commit message.

2019-08-22 18:22 UTC, vchong commented on gatekeeper/optee_gatekeeper_device.cpp
> +}
What happens if another instance of `OpteeGateKeeperDevice` class is instantiated? Do we need something like `initialized_`, similar to `connected_` in `OpteeGateKeeperDevice::connect()`, to prevent calling `gatekeeperIPC_.initialize()` again, or do subsequent (failed?) calls to `gatekeeperIPC_.initialize()` don't matter?

2019-08-22 18:22 UTC, vchong commented on gatekeeper/optee_ipc.cpp
> +    return true;
Similar to above, do we need something similar to `inUse` in `OpteeIPC::connect()`?

2019-08-22 18:22 UTC, vchong commented on keymaster/ipc/optee_keymaster_ipc.cpp
> +}
Again, something similar to `connected` in `optee_keymaster_connect()`?

2019-08-22 18:56 UTC, vchong commented on gatekeeper/optee_gatekeeper_device.cpp
> +}
Read the Client spec again and feel like this should be ok, i.e. not necessary. Same for both comments below. So, please just change the commit titles/messages above and add the appropriate Sob and Rb tags, i.e.`Signed-off-by: Olivier Masse <olivier.masse@nxp.com>` and `Reviewed by: Victor Chong <victor.chong@linaro.org>`.

2019-08-23 12:28 UTC, omasse-linaro commented on gatekeeper/optee_gatekeeper_device.cpp
> +}
Ok, modification done with the last update.

2019-08-26 06:27 UTC, vchong commented
Merged manually with minor adjustments to the commit messages. Thanks @omasse-linaro as usual for the contribution!

2019-08-26 06:27 UTC, closed without merging