attestation: mbedtls: re-implement generation of RSA root cert
linaro-swg/kmgk pull request #3
Opened 2018-12-06 22:12 UTC by igoropaniuk

1. Add creation of mbedtls_pk_context (with RSA context)
struct based on key attributes
2. Generate RSA root certificate for attestation

VTS results:
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from AttestationTest
[ RUN      ] AttestationTest.RsaAttestation
[       OK ] AttestationTest.RsaAttestation (7073 ms)
[----------] 1 test from AttestationTest (7073 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (7081 ms total)
[  PASSED  ] 1 test.
```

Previously generated root cert for attestation with ASN1 PTA
[link](https://lapo.it/asn1js/#MIICRDCCAa2gAwIBAgIBATANBgkqhkiG9w0BAQsFADBGMSAwHgYDVQQLExdBdHRlc3RhdGlvbiBSU0Egcm9vdCBDQTEQMA4GA1UEChMHQW5kcm9pZDEQMA4GA1UEAxMHQW5kcm9pZDAeFw0xODAxMDEwMDAwMDBaFw0yMTAxMDEwMDAwMDBaMEYxIDAeBgNVBAsTF0F0dGVzdGF0aW9uIFJTQSByb290IENBMRAwDgYDVQQKEwdBbmRyb2lkMRAwDgYDVQQDEwdBbmRyb2lkMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCkP8fwCKa4ECkkwmM6dOH22PZI6xLScKzzb1hg_2GblJhMGKOEqKCO-cZRnJq4WsylkDNSCqnMtbiXvYPSkFNWDI-VyWNGHph229Y-J1l0xfIDHmtlHF3AE9G3u-ZyXh-aoFsxi8j8WB3vC0FwkEySarstPgnZ0TVF9b3fWWNBCwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH_BAUwAwEB_zAdBgNVHQ4EFgQU52QIi6gmgrKNAumuVw27NewPW8swDQYJKoZIhvcNAQELBQADgYEAV8l2ycSx5TkYEV-VEyiOimdkm-6gL80hn6_Bp7qnXhJTIs4WSwjUVzjhmovx0fT2FUmpm0FW0RAyZn_FGDB259WfIgztTZGvks_ZkTARzKqVS-gaWTnBJql5XfIznRquSTnBMtoQHaGOdVk2BJz_tkdVrl9ufZQJpolzDDeJg2k)

Current result of certificate creation using mbedTLS:
[link](https://lapo.it/asn1js/#MIICZDCCAc2gAwIBAgIBATANBgkqhkiG9w0BAQsFADBGMSAwHgYDVQQLExdBdHRlc3RhdGlvbiBSU0Egcm9vdCBDQTEQMA4GA1UEChMHQW5kcm9pZDEQMA4GA1UEAxMHQW5kcm9pZDAgGA8xOTcwMDEwMTAwMDAwMFoXDTMwMTIzMTIzNTk1OVowRjEgMB4GA1UECxMXQXR0ZXN0YXRpb24gUlNBIHJvb3QgQ0ExEDAOBgNVBAoTB0FuZHJvaWQxEDAOBgNVBAMTB0FuZHJvaWQwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAKQ_x_AIprgQKSTCYzp04fbY9kjrEtJwrPNvWGD_YZuUmEwYo4SooI75xlGcmrhazKWQM1IKqcy1uJe9g9KQU1YMj5XJY0YemHbb1j4nWXTF8gMea2UcXcAT0be75nJeH5qgWzGLyPxYHe8LQXCQTJJquy0-CdnRNUX1vd9ZY0ELAgMBAAGjYDBeMAwGA1UdEwQFMAMBAf8wHQYDVR0OBBYEFOdkCIuoJoKyjQLprlcNuzXsD1vLMB8GA1UdIwQYMBaAFOdkCIuoJoKyjQLprlcNuzXsD1vLMA4GA1UdDwEB_wQEAwIBhDANBgkqhkiG9w0BAQsFAAOBgQAaKZvY8jaZL2vx-HCxHLmKLD_-glNZ8BVlPzuJxLj5MKIklHNyZOZac_j-tI1a0IVCPX9yAiKA3syMw6Mu9VaEOfLFcL-mNLRKe0FhmzVGy0hJqm-gAprEXgQ9z8W3wBUkheYus5k1vGQKVAWhSx5ZdlbyQ7ZlIQ2g5DHTvqZtag)

`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

2018-12-06 22:16 UTC, igoropaniuk commented
Will push commit for EC-related part tomorrow

2018-12-06 22:18 UTC, igoropaniuk commented on keymaster/ta/mbedtls_proxy.c
> +	ret = mbedtls_x509write_crt_set_validity(&crt, "19700101000000",
"19700101000000" should be replaced by current time.

2018-12-06 22:30 UTC, igoropaniuk commented on keymaster/ta/mbedtls_proxy.c
> +				     TEE_MALLOC_FILL_ZERO);
check ret of TEE_Malloc

2018-12-06 22:32 UTC, igoropaniuk commented on keymaster/ta/mbedtls_proxy.c
> +	rsa = (mbedtls_rsa_context *) TEE_Malloc(sizeof(mbedtls_rsa_context),
check rsa value

2018-12-06 22:36 UTC, igoropaniuk commented on keymaster/ta/include/attestation.h
> +TEE_Result mbedTLS_gen_root_rsa_cert(TEE_ObjectHandle root_rsa_key,
will put all declarations of  mbedtls wrappers to a dedicated header. (`mbedtls_proxy.h`)

2018-12-07 10:00 UTC, jockebech requested changes
Bellcore attack stuff must be fixed. Maybe @d3zd3z also should have a look at this patch.

2018-12-07 10:00 UTC, jockebech commented on keymaster/ta/asn1.c
> +	return mbedTLS_gen_root_cert_rsa(root_rsa_key, root_cert);
Now I cannot see who is calling `TA_gen_root_rsa_cert`, but it has essentially become a one line return with another function call, so is there any need to keep `TA_gen_root_rsa_cert`?

2018-12-07 10:00 UTC, jockebech commented on keymaster/ta/mbedtls_proxy.c
> +			res = TEE_ERROR_BAD_STATE;
Is this needed? It already have a "non-success" here from a "GP TEE function" (i.e, not mbed TLS).

2018-12-07 10:00 UTC, jockebech commented on keymaster/ta/mbedtls_proxy.c
> +	/* Deduce CRT */
This is subject to the [Bellcore attack](https://eprint.iacr.org/2012/553.pdf). I.e., we at least need to do some blinding here. Look at our mitigations agains this at our [security advisories](https://www.op-tee.org/security-advisories/) page, there you can see what the `LTC_RSA_CRT_HARDENING` and `LTC_RSA_BLINDING` does to mitigate against the Bellcore attack. Similar mitigations needs to be added here.

2018-12-07 10:00 UTC, jockebech commented on keymaster/ta/include/attestation.h
> +TEE_Result mbedTLS_gen_root_cert_rsa(TEE_ObjectHandle root_rsa_key,
It would be nice to have a comment here saying something about the RSA algorithm/schema in use or if there are any limitations. I.e, a general description of what kind of root cert it generates.

2018-12-07 10:00 UTC, jockebech commented on keymaster/ta/mbedtls_proxy.c
> +	if (res != TEE_SUCCESS)
if `rsa` is NULL from the beginning, then the check here is superflous (`TEE_Free` is OK to call with a NULL pointer).

2018-12-07 10:00 UTC, jockebech commented on keymaster/ta/mbedtls_proxy.c
> +	uint32_t   read_size = 0;
We usually don't line up stuff as here and on 55-61, but I have no strong opinion (if checkpatch is happy with it).

2018-12-07 15:34 UTC, igoropaniuk commented on keymaster/ta/mbedtls_proxy.c
> +			res = TEE_ERROR_BAD_STATE;
yeap, this loop was copy-pasted from `TA_gen_root_rsa_cert` in asn1.c, will fix

2018-12-07 15:34 UTC, igoropaniuk commented on keymaster/ta/include/attestation.h
> +TEE_Result mbedTLS_gen_root_cert_rsa(TEE_ObjectHandle root_rsa_key,
ok, will add. Thanks!

2018-12-07 15:39 UTC, igoropaniuk commented on keymaster/ta/mbedtls_proxy.c
> +	if (res != TEE_SUCCESS)
The point of this check is that we **should not** de-allocate rsa if creation of `mbedtls_pk_context` is successful, as pointer within `mbedtls_pk_context` points to `mbedtls_rsa_context` instance (see line 171 `pk->pk_ctx = rsa;`)

2018-12-07 15:40 UTC, igoropaniuk commented on keymaster/ta/mbedtls_proxy.c
> +	uint32_t   read_size = 0;
will fix

2018-12-07 15:42 UTC, igoropaniuk commented on keymaster/ta/asn1.c
> +	return mbedTLS_gen_root_cert_rsa(root_rsa_key, root_cert);
The initial intention was to try to introduce changes in one particular file `asn1.c` (which is in charge of communication with PTA), as it easier to track changes(`TA_gen_root_rsa_cert` is called from another file `attestation.c`). I'll "re-group" stuff when I a completely working TA with vanilla OP-TEE OS core.

2018-12-09 12:00 UTC, igoropaniuk commented
Added key importing for ecdsa

Original cert: [link](https://lapo.it/asn1js/#MIIBvTCCAWOgAwIBAgIBATAKBggqhkjOPQQDAjBGMSAwHgYDVQQLExdBdHRlc3RhdGlvbiBFQ0Mgcm9vdCBDQTEQMA4GA1UEChMHQW5kcm9pZDEQMA4GA1UEAxMHQW5kcm9pZDAeFw0xODAxMDEwMDAwMDBaFw0yMTAxMDEwMDAwMDBaMEYxIDAeBgNVBAsTF0F0dGVzdGF0aW9uIEVDQyByb290IENBMRAwDgYDVQQKEwdBbmRyb2lkMRAwDgYDVQQDEwdBbmRyb2lkMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAENBKci3e-MreDhhsinOElnFRF2Qm1i1RiS_PYploOuYvscTHpsjDWpoWJSYgUMCyD_oYxCGpdFMavcsAUOwzSbKNCMEAwDgYDVR0PAQH_BAQDAgEGMA8GA1UdEwEB_wQFMAMBAf8wHQYDVR0OBBYEFEBGaREuhsmc9154qCLPbXLHEoXXMAoGCCqGSM49BAMCA0gAMEUCIQChsabLI5qNYG4ztgH3VIbQiFpAFAX3Q3x97CswcnJqIwIgNm7c4xqz1NeoT6JGvucxS1NoR7zqHaxQAwjtgKMujus)

New cert:[link](https://lapo.it/asn1js/#MIIB4DCCAYWgAwIBAgIBATAMBggqhkjOPQQDAgUAMEYxIDAeBgNVBAsTF0F0dGVzdGF0aW9uIEVDQyByb290IENBMRAwDgYDVQQKEwdBbmRyb2lkMRAwDgYDVQQDEwdBbmRyb2lkMCAYDzE5NzAwMTAxMDAwMDAwWhcNMzAxMjMxMjM1OTU5WjBGMSAwHgYDVQQLExdBdHRlc3RhdGlvbiBFQ0Mgcm9vdCBDQTEQMA4GA1UEChMHQW5kcm9pZDEQMA4GA1UEAxMHQW5kcm9pZDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOxxMemyMNamhYlJiBQwLIP-hjEIal0Uxq9ywBQ7DNJsQdRrK1tgmTtByHJQ8xWjpStgEKacjaup29BwKPW0WcqjYDBeMAwGA1UdEwQFMAMBAf8wHQYDVR0OBBYEFPbX64JGOegWWxyniv49riblee7NMB8GA1UdIwQYMBaAFPbX64JGOegWWxyniv49riblee7NMA4GA1UdDwEB_wQEAwIBhDAMBggqhkjOPQQDAgUAA0cAMEQCIEt0WHPOvCFozZl2TB8DuIMWhddaTEYYfr4Z_CHyX7cwAiAc9Zx9EDBwvo4SwZExc1ZCnWnSmNvn9fNeTg13ucDYoQ)

2018-12-27 15:45 UTC, igoropaniuk commented
@jbech-linaro suggestion: let's keep only attestation stuff in this PR  (as you can see it already blew up to 1000 lines), I'll create another one for encoding/decoding of private keys/signatures.
Will push soon additional commit

2018-12-28 08:24 UTC, jockebech commented
> @jbech-linaro suggestion: let's keep only attestation stuff in this PR

Fine with me!

2019-07-05 04:43 UTC, vchong commented
This has been merged manually. A few remaining TODOs have been marked to be worked on later. Thanks @igoropaniuk for the great work and contribution!

2019-07-05 04:43 UTC, closed without merging

2019-07-10 15:08 UTC, vchong commented on keymaster/ta/mbedtls_proxy.c
> +	/* Deduce CRT */
Note: mbedtls by itself provides protection[1] against Bellcore so we should be ok here.

[1] https://tls.mbed.org/tech-updates/releases/mbedtls-2.8.0-2.7.2-and-2.1.11-released

2019-07-10 16:27 UTC, jbech-linaro commented on keymaster/ta/mbedtls_proxy.c
> +	/* Deduce CRT */
I'm still not convinced, at first glance I thought this looked like the same as we did here: https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/pk/rsa/rsa_exptmod.c#L137-L151 I.e., this is where we are doing the CRT operation (in the crypto lib). But the blinding starts before and ends after. Having that said. I'll need to spend a bit more time reading this piece of code + read the mbedTLS documentation a bit more to give a better and more accurate answer.